
.PHONY: all clean 123sam sam123
CC = gcc


123sam:
	$(CC) -g 123sam.c -o 123sam 
sam123:
	$(CC) -g sam123.c -o sam123 
all:
	$(CC) -g main.c -o app		-lpthread 
clean:
	rm -rf sam123	123sam	app